name: "Pull Request Labeler"
on: [ pull_request ]

jobs:
  labeler:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      labels: write
    
    steps:
    - id: Checkout
      uses: actions/checkout@v4
      
    - id: Label-the-PR
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"